spring:
  ##datasource
  datasource:
    username: beta
    password: 123456
    url: jdbc:mysql://10.32.64.20:3306/wuqing_test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    ### datasource-pool 下面为连接池的补充设置，应用到上面所有数据源中
    druid:
      # 初始化大小，最小，最大
      initial-size: 30
      min-idle: 30
      max-active: 50
      query-timeout: 10000
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,log4j
      filter:
        stat:
          log-slow-sql: false
        wall:
          config:
            multi-statement-allow: true
            none-base-statement-allow: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录 毫秒
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        allow:
        #IP黑名单 (存在共同时，deny优先于allow)
        deny:
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
  ##email
  mail:
    benmu.from: mts-orders@benmu-health.com
    host: smtp.exmail.qq.com
    username: mts-orders@benmu-health.com
    password: 901283uhkajhsdbiASDS
    port: -1
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          port: 465
          ssl.enable: true
          starttls:
            enable: true
            required: true
